//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_b8XAUX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/requisitos_concepcao_3C49BEB_b8806e00_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_b8XAUX_mEd61Af7ua88vmwActivityDetail"]="./../../PAWEB/deliveryprocesses/resources/requisitos_concepcao_3C49BEB_b8806e00_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_lnzK4X_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/impl_testes_concepcao_6299D380_1755a595_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_lnzK4X_mEd61Af7ua88vmwActivityDetail"]="./../../PAWEB/deliveryprocesses/resources/impl_testes_concepcao_6299D380_1755a595_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_z2HDsX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/analise_projeto_construcao_4CB298C2_86c68865_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_-uvaIX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/gerencia_validacao_CDF4368B_559a587e_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_-uvaIX_mEd61Af7ua88vmwActivityDetail"]="./../../PAWEB/deliveryprocesses/resources/gerencia_validacao_CDF4368B_559a587e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_sJ7bIX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/analise_projeto_elaboracao_45AAA1BA_fa1a99bc_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_dVxDQX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/analise_projeto_concepcao_D5AF3EEE_8a6b1103_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_tzuqgX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/impl_testes_elaboracao_5824897C_c94817e_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_89MkAH_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/impl_testes_validacao_62693C6F_ea0f5e62_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_89MkAH_mEd61Af7ua88vmwActivityDetail"]="./../../PAWEB/deliveryprocesses/resources/impl_testes_validacao_62693C6F_ea0f5e62_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0wActivity"]="./../../PAWEB/deliveryprocesses/resources/Concepção_757F1E16_48cf36c1_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0wActivity"]="./../../PAWEB/deliveryprocesses/resources/Elaboração_24FFB03_d5a013ae_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0wActivity"]="./../../PAWEB/deliveryprocesses/resources/Construção_4F1185A4_22619e4f_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0w,_6TeIsX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/requisitos_validacao_7F26D330_6ccf523_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_vzlCYX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/gerencia_elaboracao_8BE78703_40577f05_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_2QL5cX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/impl_testes_construcao_460953E6_801d4389_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_yeMOgX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/requisitos_construcao_6E4A9088_a85e802b_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_yeMOgX_mEd61Af7ua88vmwActivityDetail"]="./../../PAWEB/deliveryprocesses/resources/requisitos_construcao_6E4A9088_a85e802b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_yeMOgX_mEd61Af7ua88vmwWPDependency"]="./../../PAWEB/deliveryprocesses/resources/requisitos_construcao_6E4A9088_a85e802b_WPDependency.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_nrh9MX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/gerencia_concepcao_14EC4189_c9a8139e_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_Ecp0oX_mEd62TNYWta-H0w,_nrh9MX_mEd61Af7ua88vmwActivityDetail"]="./../../PAWEB/deliveryprocesses/resources/gerencia_concepcao_14EC4189_c9a8139e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0wActivity"]="./../../PAWEB/deliveryprocesses/resources/PAWEB_740E5F57_740e5f57_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_3_WxAX_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/gerencia_construcao_29183F0D_632c2eb0_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_GsTjEX_mEd62TNYWta-H0w,_3_WxAX_mEd61Af7ua88vmwActivityDetail"]="./../../PAWEB/deliveryprocesses/resources/gerencia_construcao_29183F0D_632c2eb0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_qmPa0X_mEd61Af7ua88vmwActivity"]="./../../PAWEB/deliveryprocesses/resources/requisitos_elaboracao_906D359E_44dd2da0_Activity.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_FzrR8X_mEd62TNYWta-H0w,_qmPa0X_mEd61Af7ua88vmwActivityDetail"]="./../../PAWEB/deliveryprocesses/resources/requisitos_elaboracao_906D359E_44dd2da0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_f7tAMX_lEd62TNYWta-H0w,_IG540X_mEd62TNYWta-H0wActivity"]="./../../PAWEB/deliveryprocesses/resources/Validação_A351A7F4_76a1c09f_Activity.jpeg"
contentPage.processPage.elementUrls["_EBlz13_nEd61Af7ua88vmw"] = ["Analista","PAWEB/deliveryprocesses/analista_34F71A17.html"];
contentPage.processPage.elementUrls["_7mzjZ3_nEd61Af7ua88vmw"] = ["Desenvolver Plano de Iteração ","PAWEB/deliveryprocesses/15_desenvolver_plan_iteracao_42E8F629.html"];
contentPage.processPage.elementUrls["_GIMDES7gEeajHe1jLr2ElA"] = ["Ata de Reunião","PAWEB/deliveryprocesses/ata_de_reunio_8CAE4F83.html"];
contentPage.processPage.elementUrls["_EBlz0n_nEd61Af7ua88vmw"] = ["Definir Funcionalidades e as Restrições do Sistema","PAWEB/deliveryprocesses/3_definir_funcionalidades_78B6233.html"];
contentPage.processPage.elementUrls["_LsMvGn_nEd61Af7ua88vmw"] = ["Apresentar Artefatos aos Stakeholders","PAWEB/deliveryprocesses/12_apresentar_artefatos_84534E81.html"];
contentPage.processPage.elementUrls["_pJyOdn_nEd61Af7ua88vmw"] = ["Elaborar Diagrama de Interação de Objetos","PAWEB/deliveryprocesses/7_elaborar_diagrama_de_interacao_2A04CCA4.html"];
contentPage.processPage.elementUrls["_fD8o4S-XEeaqD6yBQlJHNA"] = ["Analista","PAWEB/deliveryprocesses/analista_621C315.html"];
contentPage.processPage.elementUrls["_If81hH_nEd61Af7ua88vmw"] = ["Protótipos de Telas","PAWEB/deliveryprocesses/prototipo_de_telas_3B61EA20.html"];
contentPage.processPage.elementUrls["_4SNmKX_nEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAWEB/deliveryprocesses/especificacao_cdu_24FDFA75.html"];
contentPage.processPage.elementUrls["_pJyOhH_nEd61Af7ua88vmw"] = ["Diagrama de Interação de Objetos (UML) para o (s) Caso (s) de Uso (s) Implementado (s)","PAWEB/deliveryprocesses/diagrama_interacao_431560FA.html"];
contentPage.processPage.elementUrls["_lnzK4X_mEd61Af7ua88vmw"] = ["Implementação Concepção","PAWEB/deliveryprocesses/impl_testes_concepcao_6299D380.html"];
contentPage.processPage.elementUrls["_epiK9S8tEeaqD6yBQlJHNA"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_700815F9.html"];
contentPage.processPage.elementUrls["_95h1hDAREeafoOQIB0rwxA"] = ["Designer","PAWEB/deliveryprocesses/designer_3227518A.html"];
contentPage.processPage.elementUrls["_48R_MC-fEeaqD6yBQlJHNA"] = ["Realizara Disciplina de Análise e Projeto da Fase de Contrução","PAWEB/deliveryprocesses/10_realizar_analise_e_projeto_construcao_E6427C16.html"];
contentPage.processPage.elementUrls["_CO3uMS3aEeaR0ez2rl76Gg"] = ["Protótipos de Telas","PAWEB/deliveryprocesses/prototipo_de_telas_89884E78.html"];
contentPage.processPage.elementUrls["_7-U9MC3ZEeaR0ez2rl76Gg"] = ["Executar Reuniões com equipe","PAWEB/deliveryprocesses/11_executar_reuniao_com_equipe_9EE4BB6D.html"];
contentPage.processPage.elementUrls["__TQ4tS3ZEeaR0ez2rl76Gg"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_E9135B74.html"];
contentPage.processPage.elementUrls["_2QL5cX_mEd61Af7ua88vmw"] = ["Implementação  Construção","PAWEB/deliveryprocesses/impl_testes_construcao_460953E6.html"];
contentPage.processPage.elementUrls["_96uIVDAREeafoOQIB0rwxA"] = ["Designer","PAWEB/deliveryprocesses/designer_77AF6DC8.html"];
contentPage.processPage.elementUrls["_epiK8S8tEeaqD6yBQlJHNA"] = ["Implementador","PAWEB/deliveryprocesses/implementador__AB7633DA.html"];
contentPage.processPage.elementUrls["_OTBAEC3bEeaR0ez2rl76Gg"] = ["Executar Reuniões com equipe","PAWEB/deliveryprocesses/11_executar_reuniao_com_equipe_D580707.html"];
contentPage.processPage.elementUrls["_0xmysS-YEeaqD6yBQlJHNA"] = ["Analista","PAWEB/deliveryprocesses/analista_EBE986D6.html"];
contentPage.processPage.elementUrls["_vzlCYX_mEd61Af7ua88vmw"] = ["Liderança de Processo Elaboração","PAWEB/deliveryprocesses/gerencia_elaboracao_8BE78703.html"];
contentPage.processPage.elementUrls["_kF1zen_nEd61Af7ua88vmw"] = ["Analista","PAWEB/deliveryprocesses/analista_81B05457.html"];
contentPage.processPage.elementUrls["_a2W-0C8uEeaqD6yBQlJHNA"] = ["Realizar Comemoração de Fim de Projeto","PAWEB/deliveryprocesses/26_comemoracao_fim_4BA9C60D.html"];
contentPage.processPage.elementUrls["_1s9bK3_nEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAWEB/deliveryprocesses/especificacao_cdu_A5659B7D.html"];
contentPage.processPage.elementUrls["_NYELES-ZEeaqD6yBQlJHNA"] = ["Analista","PAWEB/deliveryprocesses/analista_D877C5C3.html"];
contentPage.processPage.elementUrls["_95rmgTAREeafoOQIB0rwxA"] = ["Implementador","PAWEB/deliveryprocesses/implementador__B874986D.html"];
contentPage.processPage.elementUrls["_vy2foDAaEea0B9VE0UjzQg"] = ["Escolher Casos de Uso para ser detalhado","PAWEB/deliveryprocesses/1_escolher_cdus_F4B4CD8B.html"];
contentPage.processPage.elementUrls["_9qHQ8C3WEeaR0ez2rl76Gg"] = ["Escolher caso de uso para validar a tecnologia","PAWEB/deliveryprocesses/escolher_caso_de_uso_para_validar_a_tecnologia_5BC8E2E6.html"];
contentPage.processPage.elementUrls["_kF-9YH_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_7AD89B40.html"];
contentPage.processPage.elementUrls["_Fvk9cC-eEeaqD6yBQlJHNA"] = ["Apresentar Artefatos aos Stakeholders","PAWEB/deliveryprocesses/12_apresentar_artefatos_AE6818C.html"];
contentPage.processPage.elementUrls["_yN0tQDAaEea0B9VE0UjzQg"] = ["Detalhamento dos Casos de Usos","PAWEB/deliveryprocesses/0_detalhar_cdu_D189ECEB.html"];
contentPage.processPage.elementUrls["_96ISdzAREeafoOQIB0rwxA"] = ["Implementador","PAWEB/deliveryprocesses/implementador__745598E6.html"];
contentPage.processPage.elementUrls["_1s9bIn_nEd61Af7ua88vmw"] = ["Identificar Mudanças nos Requisitos","PAWEB/deliveryprocesses/4_identificar_mudancas_requisitos_B368017A.html"];
contentPage.processPage.elementUrls["_b8XAUX_mEd61Af7ua88vmw"] = ["Requisitos Concepção","PAWEB/deliveryprocesses/requisitos_concepcao_3C49BEB.html"];
contentPage.processPage.elementUrls["_EyzY4X_oEd61Af7ua88vmw"] = ["Executar Testes em Build Estável no Ambiente de Desenvolvimento","PAWEB/deliveryprocesses/2_executar_testes_61D51EE2.html"];
contentPage.processPage.elementUrls["_NYNVAS-ZEeaqD6yBQlJHNA"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_F3889828.html"];
contentPage.processPage.elementUrls["_MdFWAy3XEeaR0ez2rl76Gg"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_8402CF1B.html"];
contentPage.processPage.elementUrls["_YbDnEDyBEearUKSKvvjoPg"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_F32B8D35.html"];
contentPage.processPage.elementUrls["_dVxDQX_mEd61Af7ua88vmw"] = ["Análise e Projeto Concepção","PAWEB/deliveryprocesses/analise_projeto_concepcao_D5AF3EEE.html"];
contentPage.processPage.elementUrls["_fo4SoC8uEeaqD6yBQlJHNA"] = ["Planejar Reuniões para equipe","PAWEB/deliveryprocesses/10_Planejar_reunioes_equipe_28C9C42F.html"];
contentPage.processPage.elementUrls["_EyzY43_oEd61Af7ua88vmw"] = ["Implementar Correção de Erros","PAWEB/deliveryprocesses/4_implementar_correcoes_B94808BD.html"];
contentPage.processPage.elementUrls["_i0RGAS8tEeaqD6yBQlJHNA"] = ["Diagrama de Classes de Projeto (UML)","PAWEB/deliveryprocesses/diagrama_de_classes_823CE7A0.html"];
contentPage.processPage.elementUrls["_Kw134S-eEeaqD6yBQlJHNA"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_5F489C7B.html"];
contentPage.processPage.elementUrls["_I4CsYITTEeaFPakXJR3a2g"] = ["Dividir o Problema em Casos de Uso","PAWEB/deliveryprocesses/4_dividir_em_cdus_8ADC50B8.html"];
contentPage.processPage.elementUrls["_6wXv1C-bEeaqD6yBQlJHNA"] = ["Lider de Projetos","PAWEB/deliveryprocesses/lider_DA9C63C.html"];
contentPage.processPage.elementUrls["_Gss5yX_oEd61Af7ua88vmw"] = ["Lider de Projetos","PAWEB/deliveryprocesses/lider_DD3A29B8.html"];
contentPage.processPage.elementUrls["_q33RwC9pEeaqD6yBQlJHNA"] = ["Analista","PAWEB/deliveryprocesses/analista_8C3AE23A.html"];
contentPage.processPage.elementUrls["_1s9bKX_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_4DF2B1A2.html"];
contentPage.processPage.elementUrls["_Gss5z3_oEd61Af7ua88vmw"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_F93EF5B2.html"];
contentPage.processPage.elementUrls["_NYNVBC-ZEeaqD6yBQlJHNA"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_AD7C9A37.html"];
contentPage.processPage.elementUrls["_EyzY5X_oEd61Af7ua88vmw"] = ["Executar Builds Necessários e criar um Release","PAWEB/deliveryprocesses/6_executar_build_26670101.html"];
contentPage.processPage.elementUrls["_If81g3_nEd61Af7ua88vmw"] = ["Designer","PAWEB/deliveryprocesses/designer_D8E0D1EC.html"];
contentPage.processPage.elementUrls["_96uIVzAREeafoOQIB0rwxA"] = ["Implementador","PAWEB/deliveryprocesses/implementador__7B8441FE.html"];
contentPage.processPage.elementUrls["_LsMvH3_nEd61Af7ua88vmw"] = ["Lider de Projetos","PAWEB/deliveryprocesses/lider_B1BF0665.html"];
contentPage.processPage.elementUrls["_0amjxC-fEeaqD6yBQlJHNA"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_198FADC8.html"];
contentPage.processPage.elementUrls["_epiK8C8tEeaqD6yBQlJHNA"] = ["Escolher caso de uso para ser implementado na iteração","PAWEB/deliveryprocesses/1.a_eslher_cdus_A0D853CA.html"];
contentPage.processPage.elementUrls["_i0RGBS8tEeaqD6yBQlJHNA"] = ["Especificação de Caso de Uso","PAWEB/deliveryprocesses/especificacao_cdu_46CEC9BF.html"];
contentPage.processPage.elementUrls["__TQ4sS3ZEeaR0ez2rl76Gg"] = ["Lider de Projetos","PAWEB/deliveryprocesses/lider_24817955.html"];
contentPage.processPage.elementUrls["_f42tEC-WEeaqD6yBQlJHNA"] = ["Realizar Análise e Projeto","PAWEB/deliveryprocesses/10_realizar_analise_e_projeto_7C52074E.html"];
contentPage.processPage.elementUrls["_6wE04S-bEeaqD6yBQlJHNA"] = ["Diagrama de Classes de Projeto (UML)","PAWEB/deliveryprocesses/diagrama_de_classes_F863A8D6.html"];
contentPage.processPage.elementUrls["_1s9bI3_nEd61Af7ua88vmw"] = ["Atualizar Diagrama de Casos de Uso e de Classes","PAWEB/deliveryprocesses/5_atualizar_diagramas_cdus_classes_1C41D73F.html"];
contentPage.processPage.elementUrls["_96IScTAREeafoOQIB0rwxA"] = ["Analista","PAWEB/deliveryprocesses/analista_B68CC2A1.html"];
contentPage.processPage.elementUrls["_G8xYQH_3Ed61Af7ua88vmw"] = ["Elaborar Diagrama de Interação de Objetos","PAWEB/deliveryprocesses/7_elaborar_diagrama_de_interacao_974267D8.html"];
contentPage.processPage.elementUrls["_i0RGAC8tEeaqD6yBQlJHNA"] = ["Realizar a Disciplina de Implementação para o Caso de Uso Selecionado","PAWEB/deliveryprocesses/11_implementar_cdu_779F0790.html"];
contentPage.processPage.elementUrls["_tzuqgX_mEd61Af7ua88vmw"] = ["Implementação Elaboração","PAWEB/deliveryprocesses/impl_testes_elaboracao_5824897C.html"];
contentPage.processPage.elementUrls["_Ecp0oX_mEd62TNYWta-H0w"] = ["Concepção","PAWEB/deliveryprocesses/Concepção_757F1E16.html"];
contentPage.processPage.elementUrls["_PLzRoS8tEeaqD6yBQlJHNA"] = ["Analista","PAWEB/deliveryprocesses/analista_19BADBEA.html"];
contentPage.processPage.elementUrls["_E6-FkC8uEeaqD6yBQlJHNA"] = ["Planejar Reuniões para equipe","PAWEB/deliveryprocesses/10_Planejar_reunioes_equipe_2A22B015.html"];
contentPage.processPage.elementUrls["_EyzY8H_oEd61Af7ua88vmw"] = ["Diagrama de Interação de Objetos (UML) para o (s) Caso (s) de Uso (s) Implementado (s)","PAWEB/deliveryprocesses/diagrama_interacao_697EC74E.html"];
contentPage.processPage.elementUrls["_mD_KUC8tEeaqD6yBQlJHNA"] = ["Executar Implementação do Projeto","PAWEB/deliveryprocesses/12_executar_implementacao_E2F03463.html"];
contentPage.processPage.elementUrls["_q4Y2MS9pEeaqD6yBQlJHNA"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_103C38AF.html"];
contentPage.processPage.elementUrls["_IG540X_mEd62TNYWta-H0w"] = ["Validação","PAWEB/deliveryprocesses/Validação_A351A7F4.html"];
contentPage.processPage.elementUrls["_OBKOAS8uEeaqD6yBQlJHNA"] = ["Analista","PAWEB/deliveryprocesses/analista_2D2AD23C.html"];
contentPage.processPage.elementUrls["_6wXv0S-bEeaqD6yBQlJHNA"] = ["Diagrama de Classes de Projeto (UML)","PAWEB/deliveryprocesses/diagrama_de_classes_53B5C42D.html"];
contentPage.processPage.elementUrls["_1tuIITAFEeafoOQIB0rwxA"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_2979777F.html"];
contentPage.processPage.elementUrls["_MdFWAS3XEeaR0ez2rl76Gg"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_8ACBDAF5.html"];
contentPage.processPage.elementUrls["_yeMOgX_mEd61Af7ua88vmw"] = ["Requisitos Construção","PAWEB/deliveryprocesses/requisitos_construcao_6E4A9088.html"];
contentPage.processPage.elementUrls["_3_WxAX_mEd61Af7ua88vmw"] = ["Liderança de Processo Construção","PAWEB/deliveryprocesses/gerencia_construcao_29183F0D.html"];
contentPage.processPage.elementUrls["_GHvXIS7gEeajHe1jLr2ElA"] = ["Ata de Reunião","PAWEB/deliveryprocesses/ata_de_reunio_BC97DAC9.html"];
contentPage.processPage.elementUrls["_96ISfDAREeafoOQIB0rwxA"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_F9A488EE.html"];
contentPage.processPage.elementUrls["_OBTX8C8uEeaqD6yBQlJHNA"] = ["Stakeholders","PAWEB/deliveryprocesses/stakeholders_9919F835.html"];
contentPage.processPage.elementUrls["_1s9bKH_nEd61Af7ua88vmw"] = ["Analista","PAWEB/deliveryprocesses/analista_4354D192.html"];
contentPage.processPage.elementUrls["_OBTX9y8uEeaqD6yBQlJHNA"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_6180AE8A.html"];
contentPage.processPage.elementUrls["_sJ7bIX_mEd61Af7ua88vmw"] = ["Análise e Projeto Elaboração","PAWEB/deliveryprocesses/analise_projeto_elaboracao_45AAA1BA.html"];
contentPage.processPage.elementUrls["_pJyOg3_nEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAWEB/deliveryprocesses/especificacao_cdu_E09448C6.html"];
contentPage.processPage.elementUrls["_kF1zc3_nEd61Af7ua88vmw"] = ["Identificar Mudanças nos Requisitos","PAWEB/deliveryprocesses/4_identificar_mudancas_requisitos_616665DE.html"];
contentPage.processPage.elementUrls["_EyzY6n_oEd61Af7ua88vmw"] = ["Implementador","PAWEB/deliveryprocesses/implementador__D991F736.html"];
contentPage.processPage.elementUrls["_MdFWAC3XEeaR0ez2rl76Gg"] = ["Implementação do Caso de Uso Escolhido ","PAWEB/deliveryprocesses/2_Implementar_cdu_escolhido_802DFAE5.html"];
contentPage.processPage.elementUrls["_LsMvKX_nEd61Af7ua88vmw"] = ["Protótipos de Telas","PAWEB/deliveryprocesses/prototipo_de_telas_A801C2E7.html"];
contentPage.processPage.elementUrls["_EyzY4n_oEd61Af7ua88vmw"] = ["Verificar se Necessita passar por Implementação ou se deve passar por Remodelagem","PAWEB/deliveryprocesses/3_verificar_necessidade_de_remodelagem_506E32F8.html"];
contentPage.processPage.elementUrls["_Gss5zn_oEd61Af7ua88vmw"] = ["Designer","PAWEB/deliveryprocesses/designer_90651FED.html"];
contentPage.processPage.elementUrls["_kF-9Y3_nEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAWEB/deliveryprocesses/especificacao_cdu_DCE9652B.html"];
contentPage.processPage.elementUrls["_MdFWBS3XEeaR0ez2rl76Gg"] = ["Especificação de Caso de Uso","PAWEB/deliveryprocesses/especificacao_cdu_4F5DBD14.html"];
contentPage.processPage.elementUrls["_Ya-ukDyBEearUKSKvvjoPg"] = ["Descrever Brevemente os Casos de Uso","PAWEB/deliveryprocesses/6_descrever_cdus_E458920C.html"];
contentPage.processPage.elementUrls["_If81gn_nEd61Af7ua88vmw"] = ["Confeccionar um Protótipo contendo as Telas Iniciais do Novo Sistema","PAWEB/deliveryprocesses/10_confeccionar_prototipo_7006FC27.html"];
contentPage.processPage.elementUrls["_VuIlkS7SEeajHe1jLr2ElA"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_4569A132.html"];
contentPage.processPage.elementUrls["_Gss5x3_oEd61Af7ua88vmw"] = ["Desenvolver Plano de Iteração ","PAWEB/deliveryprocesses/15_desenvolver_plan_iteracao_701B3174.html"];
contentPage.processPage.elementUrls["_3NG4oC3TEeaR0ez2rl76Gg"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_75935F33.html"];
contentPage.processPage.elementUrls["_wkTkADAVEeafoOQIB0rwxA"] = ["Detalhamento dos Casos de Usos","PAWEB/deliveryprocesses/0_detalhar_cdu_63F7E9DB.html"];
contentPage.processPage.elementUrls["_1IfjQS3YEeaR0ez2rl76Gg"] = ["Implementador","PAWEB/deliveryprocesses/implementador__5AE3265A.html"];
contentPage.processPage.elementUrls["_7mzjb3_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_67780721.html"];
contentPage.processPage.elementUrls["_LsMvHn_nEd61Af7ua88vmw"] = ["Desenvolver Plano de Iteração ","PAWEB/deliveryprocesses/15_desenvolver_plan_iteracao_48E530A0.html"];
contentPage.processPage.elementUrls["_qmPa0X_mEd61Af7ua88vmw"] = ["Requisitos Elaboração","PAWEB/deliveryprocesses/requisitos_elaboracao_906D359E.html"];
contentPage.processPage.elementUrls["_95h1gTAREeafoOQIB0rwxA"] = ["Analista","PAWEB/deliveryprocesses/analista_78334F7B.html"];
contentPage.processPage.elementUrls["_nrh9MX_mEd61Af7ua88vmw"] = ["Liderança de Processo Concepção","PAWEB/deliveryprocesses/gerencia_concepcao_14EC4189.html"];
contentPage.processPage.elementUrls["_89MkAH_mEd61Af7ua88vmw"] = ["Implementação Validação","PAWEB/deliveryprocesses/impl_testes_validacao_62693C6F.html"];
contentPage.processPage.elementUrls["_LsMvI3_nEd61Af7ua88vmw"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_7650E884.html"];
contentPage.processPage.elementUrls["__TQ4sy3ZEeaR0ez2rl76Gg"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_1DB86D7B.html"];
contentPage.processPage.elementUrls["_Gss523_oEd61Af7ua88vmw"] = ["Protótipos de Telas","PAWEB/deliveryprocesses/prototipo_de_telas_B0375CFA.html"];
contentPage.processPage.elementUrls["_Gss5yn_oEd61Af7ua88vmw"] = ["Implementador","PAWEB/deliveryprocesses/implementador__CBD33DCE.html"];
contentPage.processPage.elementUrls["_Gss50X_oEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_CFA0AEE1.html"];
contentPage.processPage.elementUrls["_GHNysS7gEeajHe1jLr2ElA"] = ["Ata de Reunião","PAWEB/deliveryprocesses/ata_de_reunio_4E340EE8.html"];
contentPage.processPage.elementUrls["_6wN-0i-bEeaqD6yBQlJHNA"] = ["Ata de Reunião","PAWEB/deliveryprocesses/ata_de_reunio_90669884.html"];
contentPage.processPage.elementUrls["_GsTjEX_mEd62TNYWta-H0w"] = ["Construção","PAWEB/deliveryprocesses/Construção_4F1185A4.html"];
contentPage.processPage.elementUrls["_-uvaIX_mEd61Af7ua88vmw"] = ["Liderança de Processo Validação","PAWEB/deliveryprocesses/gerencia_validacao_CDF4368B.html"];
contentPage.processPage.elementUrls["_EBlz0X_nEd61Af7ua88vmw"] = ["Definir Escopo do Problema","PAWEB/deliveryprocesses/2_definir_escopo_18F24E1D.html"];
contentPage.processPage.elementUrls["_dmMpMC8uEeaqD6yBQlJHNA"] = ["Executar Reuniões com equipe","PAWEB/deliveryprocesses/11_executar_reuniao_com_equipe_D2475DF5.html"];
contentPage.processPage.elementUrls["_7mzjcX_nEd61Af7ua88vmw"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_D496FF65.html"];
contentPage.processPage.elementUrls["_4AYXoC-fEeaqD6yBQlJHNA"] = ["Realizar Analise de Evolução do Projeto","PAWEB/deliveryprocesses/9_realiza_analise_evolutiva_28C7560F.html"];
contentPage.processPage.elementUrls["_95rmhjAREeafoOQIB0rwxA"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_6B9F8EA2.html"];
contentPage.processPage.elementUrls["_7mzjaX_nEd61Af7ua88vmw"] = ["Lider de Projetos","PAWEB/deliveryprocesses/lider_4B733B27.html"];
contentPage.processPage.elementUrls["_96ISdDAREeafoOQIB0rwxA"] = ["Designer","PAWEB/deliveryprocesses/designer_7080C4B0.html"];
contentPage.processPage.elementUrls["_kyWvcC-SEeaqD6yBQlJHNA"] = ["Planejar Reuniões para equipe","PAWEB/deliveryprocesses/10_Planejar_reunioes_equipe_398C6E09.html"];
contentPage.processPage.elementUrls["_1IfjRy3YEeaR0ez2rl76Gg"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_18ABFC9F.html"];
contentPage.processPage.elementUrls["_5pdXkC3ZEeaR0ez2rl76Gg"] = ["Planejar Reuniões para equipe","PAWEB/deliveryprocesses/10_Planejar_reunioes_equipe_61176C84.html"];
contentPage.processPage.elementUrls["_6wXv2C-bEeaqD6yBQlJHNA"] = ["Ata de Reunião","PAWEB/deliveryprocesses/ata_de_reunio_D23BA85B.html"];
contentPage.processPage.elementUrls["_EyzY73_oEd61Af7ua88vmw"] = ["Diagrama de Classes de Projeto (UML)","PAWEB/deliveryprocesses/diagrama_de_classes_6FDAF1A.html"];
contentPage.processPage.elementUrls["_EBlz0H_nEd61Af7ua88vmw"] = ["Cliente Define o Projeto a ser Desenvolvido","PAWEB/deliveryprocesses/1_definir_projeto_E546E0D.html"];
contentPage.processPage.elementUrls["_1s9bKn_nEd61Af7ua88vmw"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_3C8BC5B8.html"];
contentPage.processPage.elementUrls["_6TeIsX_mEd61Af7ua88vmw"] = ["Requisitos Validação","PAWEB/deliveryprocesses/requisitos_validacao_7F26D330.html"];
contentPage.processPage.elementUrls["_EBlz1n_nEd61Af7ua88vmw"] = ["Stakeholders","PAWEB/deliveryprocesses/stakeholders_CC1D4452.html"];
contentPage.processPage.elementUrls["_kF1zdH_nEd61Af7ua88vmw"] = ["Atualizar Diagrama de Casos de Uso e de Classes","PAWEB/deliveryprocesses/5_atualizar_diagramas_cdus_classes_C3E77E12.html"];
contentPage.processPage.elementUrls["_EyzY7X_oEd61Af7ua88vmw"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_AF8AC53F.html"];
contentPage.processPage.elementUrls["_Gss5zX_oEd61Af7ua88vmw"] = ["Analista","PAWEB/deliveryprocesses/analista_A1CC0BD7.html"];
contentPage.processPage.elementUrls["_EyzY5H_oEd61Af7ua88vmw"] = ["Iniciar Alterações de Modelagem em Disciplina de Análise e Projeto","PAWEB/deliveryprocesses/5_iniciar_alteracoes_de_modelagem_1BC920F1.html"];
contentPage.processPage.elementUrls["_vy_pkDAaEea0B9VE0UjzQg"] = ["Implementador","PAWEB/deliveryprocesses/implementador__A287C54C.html"];
contentPage.processPage.elementUrls["_FzrR8X_mEd62TNYWta-H0w"] = ["Elaboração","PAWEB/deliveryprocesses/Elaboração_24FFB03.html"];
contentPage.processPage.elementUrls["_vPqsUTAVEeafoOQIB0rwxA"] = ["Implementador","PAWEB/deliveryprocesses/implementador__99FC2BE8.html"];
contentPage.processPage.elementUrls["_1s9bJX_nEd61Af7ua88vmw"] = ["Realizar Análise e Projeto","PAWEB/deliveryprocesses/10_realizar_analise_e_projeto_8960CF83.html"];
contentPage.processPage.elementUrls["_EyzY8X_oEd61Af7ua88vmw"] = ["Especificação de Caso de Uso","PAWEB/deliveryprocesses/especificacao_cdu_741CA75E.html"];
contentPage.processPage.elementUrls["_GzhI4n_nEd61Af7ua88vmw"] = ["Analisar Modelo de Caso de Uso","PAWEB/deliveryprocesses/7_analisar_mod_cdu_EC3004B8.html"];
contentPage.processPage.elementUrls["__TQ4sC3ZEeaR0ez2rl76Gg"] = ["Desenvolver Plano de Iteração ","PAWEB/deliveryprocesses/15_desenvolver_plan_iteracao_19E39945.html"];
contentPage.processPage.elementUrls["_96uIUTAREeafoOQIB0rwxA"] = ["Analista","PAWEB/deliveryprocesses/analista_BDBB6BB9.html"];
contentPage.processPage.elementUrls["_GH9ZkS7gEeajHe1jLr2ElA"] = ["Ata de Reunião","PAWEB/deliveryprocesses/ata_de_reunio_41BC91C6.html"];
contentPage.processPage.elementUrls["_LsMvJX_nEd61Af7ua88vmw"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_E36FE0C8.html"];
contentPage.processPage.elementUrls["_vQHYQjAVEeafoOQIB0rwxA"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_86AD6A32.html"];
contentPage.processPage.elementUrls["_FvuHYC-eEeaqD6yBQlJHNA"] = ["Protótipos de Telas","PAWEB/deliveryprocesses/prototipo_de_telas_7681C65B.html"];
contentPage.processPage.elementUrls["_PL8bki8tEeaqD6yBQlJHNA"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_18F93F16.html"];
contentPage.processPage.elementUrls["_vPqsUDAVEeafoOQIB0rwxA"] = ["Escolher Casos de Uso para ser detalhado","PAWEB/deliveryprocesses/1_escolher_cdus_8F5E4BD8.html"];
contentPage.processPage.elementUrls["_6wE05C-bEeaqD6yBQlJHNA"] = ["Lider de Projetos","PAWEB/deliveryprocesses/lider_B257AAE5.html"];
contentPage.processPage.elementUrls["_DSXJAC8uEeaqD6yBQlJHNA"] = ["Executar Reuniões com equipe","PAWEB/deliveryprocesses/11_executar_reuniao_com_equipe_EFDA34F6.html"];
contentPage.processPage.elementUrls["_CO3uMC3aEeaR0ez2rl76Gg"] = ["Apresentar Artefatos aos Stakeholders","PAWEB/deliveryprocesses/12_apresentar_artefatos_7EEA6E68.html"];
contentPage.processPage.elementUrls["_4SNmKn_nEd61Af7ua88vmw"] = ["Diagrama de Interação de Objetos (UML) para o (s) Caso (s) de Uso (s) Implementado (s)","PAWEB/deliveryprocesses/diagrama_interacao_13970E8B.html"];
contentPage.processPage.elementUrls["_EyzY4H_oEd61Af7ua88vmw"] = ["Planejar Testes em Ambiente de Desenvolvimento","PAWEB/deliveryprocesses/1_planejar_testes_57373ED2.html"];
contentPage.processPage.elementUrls["_i0RGAy8tEeaqD6yBQlJHNA"] = ["Diagrama de Interação de Objetos (UML) para o (s) Caso (s) de Uso (s) Implementado (s)","PAWEB/deliveryprocesses/diagrama_interacao_7B73DBC6.html"];
contentPage.processPage.elementUrls["_f7tAMX_lEd62TNYWta-H0w"] = ["Processo Acadêmico Web - PAWEB","PAWEB/deliveryprocesses/PAWEB_740E5F57.html"];
contentPage.processPage.elementUrls["_Gss51n_oEd61Af7ua88vmw"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_82CBA516.html"];
contentPage.processPage.elementUrls["_4tCuUC9oEeaqD6yBQlJHNA"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_D461110C.html"];
contentPage.processPage.elementUrls["_OBTX9C8uEeaqD6yBQlJHNA"] = ["Diagrama Geral de Casos de Uso (UML)","PAWEB/deliveryprocesses/diagrama_geral_cdus_5DABDA54.html"];
contentPage.processPage.elementUrls["_8WmskS3UEeaR0ez2rl76Gg"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_D8B64845.html"];
contentPage.processPage.elementUrls["_kF-9Yn_nEd61Af7ua88vmw"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_740F8F66.html"];
contentPage.processPage.elementUrls["_0amjxy-fEeaqD6yBQlJHNA"] = ["Documento de Visão","PAWEB/deliveryprocesses/doc_visao_1D6481FE.html"];
contentPage.processPage.elementUrls["_z2HDsX_mEd61Af7ua88vmw"] = ["Análise e Projeto Construção","PAWEB/deliveryprocesses/analise_projeto_construcao_4CB298C2.html"];
contentPage.processPage.elementUrls["_vzSkgjAaEea0B9VE0UjzQg"] = ["Códigos Fontes","PAWEB/deliveryprocesses/codigos_fontes_B626313E.html"];
contentPage.processPage.elementUrls["_0amjwS-fEeaqD6yBQlJHNA"] = ["Analista","PAWEB/deliveryprocesses/analista_5F9BABB9.html"];
